// Sample Interview Questions for all phases and tiers
// This will be replaced by CSV import in production

import type { InterviewQuestion } from '../types'

export const sampleQuestions: Omit<InterviewQuestion, 'id'>[] = [
  // DISCOVERY PHASE
  {
    phase: 'DISCOVERY',
    track: 'BUSINESS',
    tier: 'UI',
    question: 'What are the top 3 user journeys to improve, and what are the desired outcomes and success metrics?',
    notes: '',
    priority: 'HIGH',
    aiReadiness: 'AI assist potential? Consider privacy concerns.',
    sourceFile: 'sample-data',
  },
  {
    phase: 'DISCOVERY',
    track: 'TECHNICAL',
    tier: 'UI',
    question: 'What UI stacks are currently in use? Is telemetry in place?',
    notes: '',
    priority: 'MEDIUM',
    aiReadiness: 'Signals for personalization later?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'DISCOVERY',
    track: 'BUSINESS',
    tier: 'API',
    question: 'Which capabilities are currently blocked by API limitations or SLA issues?',
    notes: '',
    priority: 'HIGH',
    aiReadiness: 'AI orchestration value?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'DISCOVERY',
    track: 'TECHNICAL',
    tier: 'API',
    question: 'Where are direct database calls being made? What authentication is enforced?',
    notes: '',
    priority: 'HIGH',
    aiReadiness: 'Event hooks for AI routing?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'DISCOVERY',
    track: 'BUSINESS',
    tier: 'DATA',
    question: 'Which decisions need better data freshness or accuracy? What are the required SLAs?',
    notes: '',
    priority: 'HIGH',
    aiReadiness: 'Is data labeled/contracted for AI?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'DISCOVERY',
    track: 'TECHNICAL',
    tier: 'DATA',
    question: 'Please inventory all systems, schemas, data pipelines, and quality checks.',
    notes: '',
    priority: 'HIGH',
    aiReadiness: 'Embeddings feasibility? Feature candidates?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'DISCOVERY',
    track: 'BUSINESS',
    tier: 'CLOUD',
    question: 'Are there any cost pressures or regional compliance constraints?',
    notes: '',
    priority: 'MEDIUM',
    aiReadiness: 'Predictive scaling value?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'DISCOVERY',
    track: 'TECHNICAL',
    tier: 'CLOUD',
    question: 'How is infrastructure provisioned - IaC or manual? What policies are in place?',
    notes: '',
    priority: 'MEDIUM',
    aiReadiness: 'Anomaly detection hooks?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'DISCOVERY',
    track: 'BUSINESS',
    tier: 'AI',
    question: 'What are potential 90-day safe AI wins?',
    notes: '',
    priority: 'MEDIUM',
    aiReadiness: 'Low-risk copilots/RAG opportunities?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'DISCOVERY',
    track: 'TECHNICAL',
    tier: 'AI',
    question: 'Are there any existing AI pilots? What PHI/PII/FERPA constraints exist?',
    notes: '',
    priority: 'HIGH',
    aiReadiness: 'Guardrails/evaluation harness needs?',
    sourceFile: 'sample-data',
  },

  // FOUNDATION PHASE
  {
    phase: 'FOUNDATION',
    track: 'BUSINESS',
    tier: 'UI',
    question: 'Is there an adoptable design system/language that can work across products?',
    notes: '',
    priority: 'HIGH',
    aiReadiness: 'Telemetry/consent patterns for AI?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'FOUNDATION',
    track: 'TECHNICAL',
    tier: 'UI',
    question: 'Component library scaffolding - tokens, theming, accessibility?',
    notes: '',
    priority: 'HIGH',
    aiReadiness: 'Event/log hooks for AI signals?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'FOUNDATION',
    track: 'BUSINESS',
    tier: 'API',
    question: 'What are the agreed SLAs and partner dependencies?',
    notes: '',
    priority: 'HIGH',
    aiReadiness: 'Tolerance for AI fallbacks/Human-in-loop?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'FOUNDATION',
    track: 'TECHNICAL',
    tier: 'API',
    question: 'Gateway, auth, caching, idempotency, error contracts?',
    notes: '',
    priority: 'HIGH',
    aiReadiness: 'Event bus + tracing for AI orchestration?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'FOUNDATION',
    track: 'BUSINESS',
    tier: 'DATA',
    question: 'Which domains should we onboard first for contracts/lineage?',
    notes: '',
    priority: 'HIGH',
    aiReadiness: 'Roadmap for AI-enabling datasets?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'FOUNDATION',
    track: 'TECHNICAL',
    tier: 'DATA',
    question: 'Contracts, CDC, dbt/ADF, lineage (Purview)?',
    notes: '',
    priority: 'HIGH',
    aiReadiness: 'Vector store/embeddings/feature store skeleton?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'FOUNDATION',
    track: 'BUSINESS',
    tier: 'CLOUD',
    question: 'What budget guardrails and tagging standards should we establish?',
    notes: '',
    priority: 'MEDIUM',
    aiReadiness: 'FinOps ML targets?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'FOUNDATION',
    track: 'TECHNICAL',
    tier: 'CLOUD',
    question: 'ALZ/IaC/policy-as-code/secrets management?',
    notes: '',
    priority: 'HIGH',
    aiReadiness: 'Predictive scaling & anomaly hooks?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'FOUNDATION',
    track: 'BUSINESS',
    tier: 'AI',
    question: 'What governance is needed for prompts/models/audits?',
    notes: '',
    priority: 'HIGH',
    aiReadiness: 'Eval cadence & acceptance thresholds?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'FOUNDATION',
    track: 'TECHNICAL',
    tier: 'AI',
    question: 'Eval harness, guardrails, key rotation, audit logging?',
    notes: '',
    priority: 'HIGH',
    aiReadiness: 'Red-teaming & rollback procedures?',
    sourceFile: 'sample-data',
  },

  // MODERNIZATION PHASE
  {
    phase: 'MODERNIZATION',
    track: 'BUSINESS',
    tier: 'UI',
    question: 'Which user flows should migrate first? How do we measure adoption?',
    notes: '',
    priority: 'HIGH',
    aiReadiness: 'AI concierge value vs risk?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'MODERNIZATION',
    track: 'TECHNICAL',
    tier: 'UI',
    question: 'Migrate to component library; add telemetry/feature flags.',
    notes: '',
    priority: 'HIGH',
    aiReadiness: 'Personalization experiment plan?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'MODERNIZATION',
    track: 'BUSINESS',
    tier: 'API',
    question: 'Which partner integrations/ecosystems should we enable?',
    notes: '',
    priority: 'MEDIUM',
    aiReadiness: 'AI-based prioritization or routing?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'MODERNIZATION',
    track: 'TECHNICAL',
    tier: 'API',
    question: 'Gateway SLOs, back-pressure, retries?',
    notes: '',
    priority: 'HIGH',
    aiReadiness: 'Semantic router to AI services?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'MODERNIZATION',
    track: 'BUSINESS',
    tier: 'DATA',
    question: 'What KPIs measure freshness/accuracy value?',
    notes: '',
    priority: 'MEDIUM',
    aiReadiness: 'Predictive KPI targets?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'MODERNIZATION',
    track: 'TECHNICAL',
    tier: 'DATA',
    question: 'CDC/dbt/ADF jobs, tests, semantic models?',
    notes: '',
    priority: 'HIGH',
    aiReadiness: 'Feature store/drift detection live?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'MODERNIZATION',
    track: 'BUSINESS',
    tier: 'CLOUD',
    question: 'Which scaling scenarios to test (seasonal/campaigns)?',
    notes: '',
    priority: 'MEDIUM',
    aiReadiness: 'Predictive scaling targets?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'MODERNIZATION',
    track: 'TECHNICAL',
    tier: 'CLOUD',
    question: 'IaC deploys, autoscale tests, blue/green, canary?',
    notes: '',
    priority: 'HIGH',
    aiReadiness: 'Predictive scaling baseline learned?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'MODERNIZATION',
    track: 'BUSINESS',
    tier: 'AI',
    question: 'Where should we expand copilots/RAG capabilities?',
    notes: '',
    priority: 'MEDIUM',
    aiReadiness: 'Is governance ready?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'MODERNIZATION',
    track: 'TECHNICAL',
    tier: 'AI',
    question: 'Deploy RAG/ML Ops; enforce guardrails + Human-in-loop?',
    notes: '',
    priority: 'HIGH',
    aiReadiness: 'Eval metrics passing? Rollback path verified?',
    sourceFile: 'sample-data',
  },

  // INTELLIGENCE PHASE (AI-Included Path)
  {
    phase: 'INTELLIGENCE',
    track: 'BUSINESS',
    tier: 'UI',
    question: 'What is the impact of personalization/recommendations on outcomes?',
    notes: '',
    priority: 'MEDIUM',
    aiReadiness: 'Human override/transparency thresholds?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'INTELLIGENCE',
    track: 'TECHNICAL',
    tier: 'UI',
    question: 'Conversational UX; edge prompt patterns/guardrails?',
    notes: '',
    priority: 'MEDIUM',
    aiReadiness: 'PII boundary and retention verified?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'INTELLIGENCE',
    track: 'BUSINESS',
    tier: 'API',
    question: 'What are the benefits of intelligent routing/prioritization?',
    notes: '',
    priority: 'MEDIUM',
    aiReadiness: 'Policy constraints for automated actions?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'INTELLIGENCE',
    track: 'TECHNICAL',
    tier: 'API',
    question: 'Event orchestration & agents with approvals?',
    notes: '',
    priority: 'MEDIUM',
    aiReadiness: 'Safety policies and rate limits configured?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'INTELLIGENCE',
    track: 'BUSINESS',
    tier: 'DATA',
    question: 'Which predictive/optimization models provide competitive advantage?',
    notes: '',
    priority: 'HIGH',
    aiReadiness: 'Acceptance of probabilistic results?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'INTELLIGENCE',
    track: 'TECHNICAL',
    tier: 'DATA',
    question: 'Feature store; auto-profiling; drift detection?',
    notes: '',
    priority: 'HIGH',
    aiReadiness: 'Retraining cadence and contracts enforced?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'INTELLIGENCE',
    track: 'BUSINESS',
    tier: 'CLOUD',
    question: 'What FinOps policies can optimize cost per transaction?',
    notes: '',
    priority: 'MEDIUM',
    aiReadiness: 'Automated policy tuning constraints?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'INTELLIGENCE',
    track: 'TECHNICAL',
    tier: 'CLOUD',
    question: 'Predictive autoscaling; chaos tests; failover drills?',
    notes: '',
    priority: 'MEDIUM',
    aiReadiness: 'Anomaly explanations recorded?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'INTELLIGENCE',
    track: 'BUSINESS',
    tier: 'AI',
    question: 'Executive audit requirements for AI at scale?',
    notes: '',
    priority: 'HIGH',
    aiReadiness: 'Reporting cadence and metrics?',
    sourceFile: 'sample-data',
  },
  {
    phase: 'INTELLIGENCE',
    track: 'TECHNICAL',
    tier: 'AI',
    question: 'Automate evals, red-team, telemetry, retraining?',
    notes: '',
    priority: 'HIGH',
    aiReadiness: 'Human-in-the-loop checkpoints live?',
    sourceFile: 'sample-data',
  },
]
