name: Backup Database Schema

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'

  workflow_dispatch: # Allow manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Backup schema
        env:
          PGPASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        run: |
          BACKUP_FILE="backup-$(date +%Y%m%d-%H%M%S).sql"

          # Dump schema only (no data)
          pg_dump "postgresql://postgres@db.$SUPABASE_PROJECT_ID.supabase.co:5432/postgres?sslmode=require" \
            --schema-only \
            --no-owner \
            --no-privileges \
            > "$BACKUP_FILE"

          echo "✅ Schema backed up to $BACKUP_FILE"
          echo "BACKUP_FILE=$BACKUP_FILE" >> $GITHUB_ENV

      - name: Upload backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: schema-backup-${{ github.run_number }}
          path: ${{ env.BACKUP_FILE }}
          retention-days: 30

      - name: Commit backup to repository
        run: |
          mkdir -p backups
          mv ${{ env.BACKUP_FILE }} backups/

          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add backups/
          git commit -m "chore: automated schema backup $(date +%Y-%m-%d)" || echo "No changes to commit"
          git push || echo "Nothing to push"
